# TCL File Generated by Component Editor 21.1
# Tue Nov 29 16:30:56 CET 2022
# DO NOT MODIFY


# 
# GPU "GPU" v1.0
#  2022.11.29.16:30:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module GPU
# 
set_module_property DESCRIPTION ""
set_module_property NAME GPU
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME GPU
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gpu_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gpu_top.sv SYSTEM_VERILOG PATH ../rtl_src/gpu_top.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AXI_ADDR_WIDTH INTEGER 7 ""
set_parameter_property AXI_ADDR_WIDTH DEFAULT_VALUE 7
set_parameter_property AXI_ADDR_WIDTH DISPLAY_NAME AXI_ADDR_WIDTH
set_parameter_property AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property AXI_ADDR_WIDTH UNITS None
set_parameter_property AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_ADDR_WIDTH DESCRIPTION ""
set_parameter_property AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock process_clk
set_interface_property interrupt_sender associatedReset process_reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point process_clk
# 
add_interface process_clk clock end
set_interface_property process_clk clockRate 0
set_interface_property process_clk ENABLED true
set_interface_property process_clk EXPORT_OF ""
set_interface_property process_clk PORT_NAME_MAP ""
set_interface_property process_clk CMSIS_SVD_VARIABLES ""
set_interface_property process_clk SVD_ADDRESS_GROUP ""

add_interface_port process_clk aclk clk Input 1


# 
# connection point pixel_clk
# 
add_interface pixel_clk clock end
set_interface_property pixel_clk clockRate 0
set_interface_property pixel_clk ENABLED true
set_interface_property pixel_clk EXPORT_OF ""
set_interface_property pixel_clk PORT_NAME_MAP ""
set_interface_property pixel_clk CMSIS_SVD_VARIABLES ""
set_interface_property pixel_clk SVD_ADDRESS_GROUP ""

add_interface_port pixel_clk pixel_clock clk Input 1


# 
# connection point slave
# 
add_interface slave axi4lite end
set_interface_property slave associatedClock process_clk
set_interface_property slave associatedReset process_reset
set_interface_property slave readAcceptanceCapability 1
set_interface_property slave writeAcceptanceCapability 1
set_interface_property slave combinedAcceptanceCapability 1
set_interface_property slave readDataReorderingDepth 1
set_interface_property slave bridgesToMaster ""
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave awaddr awaddr Input "((AXI_ADDR_WIDTH-1)) - (0) + 1"
add_interface_port slave awprot awprot Input 3
add_interface_port slave awvalid awvalid Input 1
add_interface_port slave awready awready Output 1
add_interface_port slave wdata wdata Input 32
add_interface_port slave wstrb wstrb Input 4
add_interface_port slave wvalid wvalid Input 1
add_interface_port slave wready wready Output 1
add_interface_port slave bresp bresp Output 2
add_interface_port slave bvalid bvalid Output 1
add_interface_port slave bready bready Input 1
add_interface_port slave araddr araddr Input "((AXI_ADDR_WIDTH-1)) - (0) + 1"
add_interface_port slave arprot arprot Input 3
add_interface_port slave arvalid arvalid Input 1
add_interface_port slave arready arready Output 1
add_interface_port slave rdata rdata Output 32
add_interface_port slave rresp rresp Output 2
add_interface_port slave rvalid rvalid Output 1
add_interface_port slave rready rready Input 1


# 
# connection point pixel_reset
# 
add_interface pixel_reset reset end
set_interface_property pixel_reset associatedClock process_clk
set_interface_property pixel_reset synchronousEdges DEASSERT
set_interface_property pixel_reset ENABLED true
set_interface_property pixel_reset EXPORT_OF ""
set_interface_property pixel_reset PORT_NAME_MAP ""
set_interface_property pixel_reset CMSIS_SVD_VARIABLES ""
set_interface_property pixel_reset SVD_ADDRESS_GROUP ""

add_interface_port pixel_reset pixel_resetn reset_n Input 1


# 
# connection point process_reset
# 
add_interface process_reset reset end
set_interface_property process_reset associatedClock process_clk
set_interface_property process_reset synchronousEdges DEASSERT
set_interface_property process_reset ENABLED true
set_interface_property process_reset EXPORT_OF ""
set_interface_property process_reset PORT_NAME_MAP ""
set_interface_property process_reset CMSIS_SVD_VARIABLES ""
set_interface_property process_reset SVD_ADDRESS_GROUP ""

add_interface_port process_reset aresetn reset_n Input 1


# 
# connection point vga_master_1
# 
add_interface vga_master_1 avalon_streaming start
set_interface_property vga_master_1 associatedClock pixel_clk
set_interface_property vga_master_1 associatedReset pixel_reset
set_interface_property vga_master_1 dataBitsPerSymbol 10
set_interface_property vga_master_1 errorDescriptor ""
set_interface_property vga_master_1 firstSymbolInHighOrderBits true
set_interface_property vga_master_1 maxChannel 0
set_interface_property vga_master_1 readyLatency 0
set_interface_property vga_master_1 ENABLED true
set_interface_property vga_master_1 EXPORT_OF ""
set_interface_property vga_master_1 PORT_NAME_MAP ""
set_interface_property vga_master_1 CMSIS_SVD_VARIABLES ""
set_interface_property vga_master_1 SVD_ADDRESS_GROUP ""

add_interface_port vga_master_1 m_data data Output 30
add_interface_port vga_master_1 m_ready ready Input 1
add_interface_port vga_master_1 m_startofpacket startofpacket Output 1
add_interface_port vga_master_1 m_valid valid Output 1
add_interface_port vga_master_1 m_endofpacket endofpacket Output 1

